version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stocks-backend
    working_dir: /home/backend
    volumes:
      - "./backend:/home/backend"
      - "backend_node_modules:/home/backend/node_modules"
    ports:
      - "6969:6969"
    links:
      - "db"
    networks:
      - stocks-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stocks-frontend
    working_dir: /home/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    volumes:
      - "./frontend:/home/frontend"
      - "client_node_modules:/home/frontend/node_modules"
    ports:
      - "3000:3000"
    networks:
      - stocks-network

  db:
    image: postgres:latest
    container_name: stocks-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - stocks-network

volumes:
  backend_node_modules:
  client_node_modules:
networks:
  stocks-network:
