version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    container_name: backend
    working_dir: /home/stocks/app
    command: "yarn start"
    env_file: ./backend/.env
    volumes:
      - "./backend:/home/stocks/app"
      - "backend_node_modules:/home/stocks/app/node_modules"
    networks:
      - stocks-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /home/stocks/app
    command: "yarn start"
    volumes:
      - "./frontend:/home/stocks/app"
      - "frontend_node_modules:/home/stocks/app/node_modules"
    ports:
      - "3000:3000"
    networks:
      - stocks-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:
networks:
  stocks-network:
