name: Lint and format CI

on: push

jobs:
  run-frontend-linters:
    name: Run frontend linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Run linters
        working-directory: ./frontend
        run: |
          yarn run lint

  run-frontend-formatting:
    name: Run frontend formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write frontend/src/**/*.{js,css}
          commit_message: 'Prettified code'

  run-backend-linters:
    name: Run backend linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        working-directory: ./backend
        run: yarn install

      - name: Run linters
        working-directory: ./backend
        run: |
          yarn run lint

  run-backend-formatting:
    name: Run frontend formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write backend/**.js
          commit_message: 'Prettified backend code'
